package iaroslav.baranov.tracklog.processor;

public enum ExecutionCommandType {
    SELECT_PROCEDURE_FOR_EXECUTION,
    EXECUTE_CONTROL_STRUCTURE,
    EXECUTE_BUILD_IN_PREDICATE,
    EXECUTE_USER_DEFINED_PROCEDURE,
    EXECUTE_USER_DEFINED_PROCEDURE_NO_MORE_CLAUSES,
    EXECUTE_CUT,
    BACKTRACKING,
    HALT
}
